spring.application.name=user-service

server.servlet.context-path=/users

server.port=9020
jwt.secretKey = iuf8hf80ergf8rbv80u3hg8bg8urg8kh9r8hg3rhg894rhg

spring.datasource.url = jdbc:postgresql://localhost:5432/userDB
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.jpa.hibernate.ddl-auto=update


eureka.client.service-url.defaultZone=http://192.168.19.1:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


